### PR TITLE
Upgrade build

### PR DESCRIPTION
**Pull request by gfredericks**
This includes several different commits that I made in the pursuit of being able to mix in external clojurescript code with a presentation. Feel free to pick and choose if you don't like all of it.

### CODE REVIEW

**Comment by jblomo** [comment]
This works well for me except two issues:
- there is another pull request which requires `one` for history, so it may not be a good idea to remove this dependency
- The README.md is not updated with the new build procedure

I've merged this branch into my `bleeding` branch if you want to try it out.

**Comment by gfredericks** [comment]
I'm not too attached to the `one` part -- if I take that out and update the `README.md` it'll be good?

**Comment by jblomo** [comment]
It's up to @stuartsierra , I'm just a random user.  The animation branch was the other user of `one`, but it looks like that is unlikely to get merged.  Removing may be a good idea.

**Comment by stuartsierra** [comment]
Superseded by later commits.

**Pull request closed without merging**
