### PR TITLE
Added History-api support.

### PR DESCRIPTION
**Pull request by neotyk**
This allows navigating via Back and Forward browsers buttons.

Please review it.
Following issues are still present:
- Navigating back to /example.html
  Don't know how to go back to initial view
- On navigating via browser buttons navigate event is triggered twice.

### CODE REVIEW

**Comment by stuartsierra** [comment]
It works and is an addition I would like to have. Thanks!

Comments:
- You can return to the initial (non-slideshow) view by calling `leave-slideshow-mode`
- Use `reset!` instead of `(swap! ... (constantly x))`
- Please use plain, lower-case symbol for globals: `history` instead of `*HISTORY*`

I don't know how to fix the problem of duplicate events from browser navigation buttons, but I think this needs to be fixed before I can use the patch. It will become important if/when slide transitions get added.

**Comment by neotyk** [comment]
Two events are fired in browser after navigation:
- PopStateEvent is fired
- HashChangeEvent is fired

Both events get flatten to goog.history.Event at http://closure-library.googlecode.com/svn/docs/closure_goog_history_html5history.js.source.html#line253
From that moment on there is no way to distinguish what event was fired.

As a workaround I will check in history-handler if slide change is needed, otherwise noop.

**Comment by neotyk** [comment]
HTML5 History API integration is ready.
Even than Google Closure Library flattens popstate and hashchange events, slide will be changed only once.

**Comment by jblomo** [comment]
This is working well for me with one exception: when I click on a section in 'normal' mode, it jumps into 'projection' mode.  I'd prefer the modes be separate History events.

**Comment by stuartsierra** [comment]
Patch no longer applies.

**Pull request closed without merging**
